---
name: Pull request checks

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, unlocked, edited]

jobs:
  run-test:
    uses: ./.github/workflows/test.yml
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
  run-build:
    needs: run-test
    uses: ./.github/workflows/rpm.yml
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
