---
name: Pull request checks

on:
  pull_request:
    branches: [master]
    types: [synchronize]

jobs:
  run-test:
    uses: $GITHUB_REPOSITORY/.github/workflows/test.yml@master

  run-build:
    needs: run-test
    uses: $GITHUB_REPOSITORY/.github/workflows/rpm.yml@master
