---
name: Pull request checks

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, unlocked, edited]

jobs:
  run-test:
    uses: ./.github/workflows/test.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  run-build:
    needs: run-test
    uses: ./.github/workflows/rpm.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
