---
name: Create RPM

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GHCR_PAT:
        required: true

jobs:
  rpm:
    runs-on: ubuntu-latest
    environment: test-env
    env:
      ARCH: ${{ github.runner.arch }}
    container:
      image: ghcr.io/${{ github.repository_owner }}/docker-builder:latest
      credentials:
        username: $GITHUB_REPOSITORY_OWNER
        password: ${{ secrets.GHCR_PAT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env variables
        run: |
          echo "ARCH=$(uname -i)" >> $GITHUB_ENV
          echo "VERSION=$(sed -n 's/Version: //p' modulemd-tools.spec | head -1)" >> $GITHUB_ENV
      - name: Create sources
        run: |
          git archive HEAD --prefix=modulemd-tools-$VERSION/ -o modulemd-tools-$VERSION.tar
          gzip modulemd-tools-$VERSION.tar
      - name: Setup directory tree
        run: |
          rpmdev-setuptree
      - name: Build SRPM & RPM
        run: |
          cp modulemd-tools-$VERSION.tar.gz $HOME/rpmbuild/SOURCES/
          cp modulemd-tools.spec $HOME/rpmbuild/SPECS/
          rpmbuild -ba $HOME/rpmbuild/SPECS/modulemd-tools.spec
