---
name: Create RPM

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  rpm:
    runs-on: ubuntu-latest
    environment: test-env
    env:
      ARCH: ${{ github.runner_arch }}
    container:
      image: ghcr.io/rpm-software-management/dnf-ci-host
      # image: ${{ secrets.DOCKERHUB_USERNAME }}/modulemd_tools_tests:latest
      # credentials:
      #   username: ${{ secrets.DOCKERHUB_USERNAME }}
      #   password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env variables
        run: |
          echo "ARCH=$(uname -i)" >> $GITHUB_ENV
          echo "VERSION=$(sed -n 's/Version: //p' modulemd-tools.spec | head -1)" >> $GITHUB_ENV
      - name: Create sources
        run: |
          git archive HEAD --prefix=modulemd-tools-$VERSION/ -o modulemd-tools-$VERSION.tar
          gzip modulemd-tools-$VERSION.tar
      - name: Setup directory tree
        run: |
          rpmdev-setuptree
      - name: Build SRPM & RPM
        run: |
          cp modulemd-tools-$VERSION.tar.gz $HOME/rpmbuild/SOURCES/
          cp modulemd-tools.spec $HOME/rpmbuild/SPECS/
          rpmbuild -ba $HOME/rpmbuild/SPECS/modulemd-tools.spec
