---
name: Tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: test-env
    environment: test-env
    env:
      SITEPACKAGES: true
    container:
      image: ghcr.io/mkulik-rh/docker-builder:latest
      credentials:
        username: mkulik-rh
        password: ${{ secrets.GHCR_PAT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linter
        run: |
          tox -vvv -e flake8
      - name: Run tests
        run: |
          tox -vvv -e py310