---
name: Tests

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GHCR_PAT:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test-env
    env:
      SITEPACKAGES: true
    container:
      image: ghcr.io/${{ github.repository_owner }}/docker-builder:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linter
        run: |
          tox -vvv -e flake8
      - name: Run tests
        run: |
          tox -vvv -e py310
