---
name: Tests

on:
  workflow_dispatch:
    inputs:
      test-type:
        type: choice
        required: true
        description: Select type of tests
        options:
          - flake8
          - py310
  workflow_call:
    inputs:
      test-type:
        required: true
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  test:
    name: Run ${{ inputs.test-type }}
    runs-on: ubuntu-latest
    environment: test-env
    env:
      SITEPACKAGES: true
    container:
      image: ${{ secrets.DOCKERHUB_USERNAME }}/modulemd_tools_tests:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run ${{ inputs.test-type }}
        run: |
          tox -vvv -e ${{ inputs.test-type }}
