---
name: Tests

on:
  workflow_dispatch:
    inputs:
      test_type:
        type: choice
        required: true
        description: Select type of tests
        options:
          - flake8
          - py310
  workflow_call:
    inputs:
      test_type:
        required: true
        type: string

jobs:
  test:
    name: Run ${{ inputs.test_type }}
    runs-on: ubuntu-latest
    environment: test-env
    env:
      SITEPACKAGES: true
    container:
      image: ghcr.io/rpm-software-management/dnf-ci-host
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          dnf install -y tox
      - name: Run ${{ github.event.inputs.test_type }}
        run: |
          tox -vvv -e ${{ github.event.inputs.test_type }}
