---
name: Tests

on:
  workflow_dispatch:
    inputs:
      test_type:
        type: choice
        required: true
        description: Select type of tests
        options:
          - flake8
          - py310
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
  workflow_call:
    inputs:
      test_type:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  test:
    name: Run ${{ inputs.test_type }}
    runs-on: ubuntu-latest
    environment: test-env
    env:
      SITEPACKAGES: true
    container:
      image: ghcr.io/rpm-software-management/dnf-ci-host
      # image: test/modulemd_tools_tests:latest
      # credentials:
      #   username: ${{ secrets.DOCKERHUB_USERNAME }}
      #   password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run ${{ inputs.test_type }}
        run: |
          tox -vvv -e ${{ inputs.test_type }}
